load(":fswtarget.bzl", "fswtarget_desktop")
load(":fswtarget.bzl", "fswtarget_teensy")

fswtarget_desktop(name = "hootl_leader")
fswtarget_desktop(name = "hootl_follower")
fswtarget_desktop(name = "realtime_hootl_leader")
fswtarget_desktop(name = "realtime_hootl_follower")

fswtarget_teensy(name = "hitl_leader")
fswtarget_teensy(name = "hitl_follower")
fswtarget_teensy(name = "realtime_hitl_leader")
fswtarget_teensy(name = "realtime_hitl_follower")

fswtarget_teensy(name = "flight_leader")
fswtarget_teensy(name = "flight_follower")
