cc_library(
    name = "json",
    hdrs = ["json/json.hpp"],
    linkstatic = True,
    visibility = ["//visibility:public"],
)

cc_library(
    name = "memuse",
    hdrs = ["memuse/memuse.h"],
    linkstatic = True,
    visibility = ["//visibility:public"],
)
