load(":common.bzl", "common_library")

common_library(name = "common_desktop_fsw_ut", defines = ["DESKTOP", "UNIT_TEST"])

common_library(name = "common_desktop_fsw", defines = ["DESKTOP"])
common_library(name = "common_gsw_ut", defines = ["GSW", "DESKTOP", "UNIT_TEST"])

common_library(name = "common_gsw", defines = ["GSW", "DESKTOP"])
common_library(name = "common_teensy", defines = [])
common_library(name = "common_teensy_ut", defines = ["UNIT_TEST"])
