# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo apt-get install lcov
        sudo gem install coveralls-lcov
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        platformio update

    - name: Desktop flight software tests
      run: ./tools/run_desktop_flight_tests.sh
    
    - name: Common software tests
      run: ./tools/run_common_software_tests.sh
      
    - name: Ground software tests
      run: ./tools/run_ground_tests.sh
        
    - name: Verify FSW Teensy builds
      run: ./tools/verify_teensy_builds.sh
